# =========================
# -- Variables
# =========================
# Values come from terraform.tfvars, generated by scripts/gcp/sync-env.sh
# out of .env (common) + .env.gcp.

variable "project_id" {
  description = "GCP project ID (created by terraform/gcp/persistent)"
  type        = string
}

variable "zone" {
  description = "Zone for the bootstrap VM"
  type        = string
  default     = "northamerica-northeast2-a" # Toronto
}

variable "machine_type" {
  description = "Bootstrap VM machine type"
  type        = string
  default     = "e2-standard-8"
}

variable "repo_url" {
  description = "Unity project repo — decides which game-ci editor image gets baked"
  type        = string
}

variable "platform" {
  description = "Build target platform — decides the game-ci image variant"
  type        = string
}

variable "artifact_bucket_name" {
  description = "Artifacts bucket (persistent output) — holds the downloader-gcp binary under bootstrap/"
  type        = string
}

variable "novnc_allowed_cidr" {
  description = "CIDR allowed to reach noVNC (6080) — defense-in-depth on top of the VNC password"
  type        = string
}

variable "admin_password" {
  description = "VNC password noVNC prompts for on Connect (ADMIN_PASSWORD in .env)"
  type        = string
  sensitive   = true
}

variable "github_token" {
  description = "Optional GitHub PAT — empty for public repos, required for private (version detection on the VM)"
  type        = string
  sensitive   = true
  default     = ""
}
